#
# Copyright Strimzi authors.
# License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
#
kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: strimzi-traffic-generator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: strimzi-traffic-generator
    spec:
      restartPolicy: Always
      containers:
        - name: traffic-generator
          image: quay.io/jary/go-stoker:latest
          volumeMounts:
            - name: cluster-ca
              mountPath: /etc/cluster-ca
              readOnly: true
            - name: client-ca
              mountPath: /etc/client-ca
              readOnly: true
            - name: client-ca-cert
              mountPath: /etc/client-ca-cert
              readOnly: true
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: 'tenant2-kafka-bootstrap-strimzi-tenant2.apps.mw-ocp4.cloud.lab.eng.bos.redhat.com:443'
            - name: TOPIC
              value: 'traffic-gen-topic'
            - name: SEND_RATE
              value: '5'
            - name: PRODUCER_CLIENT_ID
              value: 'traffic-gen-client'
            - name: TLS_ENABLED
              value: true
      volumes:
        - name: cluster-ca
          secret:
            secretName: tenant2-cluster-ca-cert
            defaultMode: 288
        - name: client-ca-cert
          secret:
            secretName: tenant2-clients-ca-cert
            defaultMode: 288
        - name: client-ca
          secret:
            secretName: tenant2-clients-ca
            defaultMode: 288
          imagePullPolicy: IfNotPresent
      dnsPolicy: ClusterFirst
  triggers:
    - type: ConfigChange